CREATE TABLE Author
(
 Id INT IDENTITY(1, 1),
 Name NVARCHAR(255) NOT NULL,
 Surname NVARCHAR(255) NULL
CONSTRAINT PK_Author PRIMARY KEY CLUSTERED 
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO [dbo].[Author]
           ([Name]
           ,[Surname])
     VALUES
           ('Johnny'
           ,'Test')
GO

CREATE TABLE Post
(
Id INT IDENTITY(1, 1),
AuthorId INT NOT NULL,
Title NVARCHAR(2000),
Description NVARCHAR(MAX),
Content NTEXT,
CONSTRAINT PK_Post PRIMARY KEY CLUSTERED 
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE Post WITH NOCHECK ADD CONSTRAINT [FK_Post_Authod_Id] FOREIGN KEY(AuthorId)
REFERENCES [dbo].Author ([Id])
GO